### ISSUE TITLE
Protobuf file - PID packet not coherent

### ISSUE THREAD

**Issue by tictacmenthe** [outech-robotic/hl-flowing-clean-arch#76]
https://github.com/outech-robotic/hl-flowing-clean-arch/blob/d55250b31cacd7c4ffbb7a779b9c39bbc5e7969b/src/proto.pb#L20-L29

We can't send just one PID config (ID+kp/ki/kd) AND send acceleration/speed limits with it, it doesn't make sense, as PID and limits are mostly unrelated.

Either we :
- Separate into MotionLimitMsg(**uint32** translation_speed, rotation_speed, wheel_speed, wheel_acceleration) and PIDConfigMsg(**uint8** PID_ID, **uint32** kp, ki, kd)
- Change name into MotionConfigMsg and add all PIDs in it (translation_kp, translation_ki, translation_kd, rotation_kp... left_speed_kp... right_speed_kd) without a PID ID in it

First choice sounds better to me, and is compatible with current motor board software.
It also separates entirely PIDs and limits...

**Comment by bonnetn** [comment]
do it :D

**Comment by Melanie-Co** [comment]
I approve :)

**Comment by tictacmenthe** [comment]
Fine, I'll do it.
I have to do everything here anyway :mask:
