### ISSUE TITLE
Protobuf file - pump/servo ID too big

### ISSUE THREAD

**Issue by tictacmenthe** [outech-robotic/hl-flowing-clean-arch#77]
SetPIDMsg , PumpAndValveMsg and ServoMsg's id/pid_id fields should be uint8, not 32

https://github.com/outech-robotic/hl-flowing-clean-arch/blob/d55250b31cacd7c4ffbb7a779b9c39bbc5e7969b/src/proto.pb#L56

https://github.com/outech-robotic/hl-flowing-clean-arch/blob/d55250b31cacd7c4ffbb7a779b9c39bbc5e7969b/src/proto.pb#L51

https://github.com/outech-robotic/hl-flowing-clean-arch/blob/d55250b31cacd7c4ffbb7a779b9c39bbc5e7969b/src/proto.pb#L21

**Comment by bonnetn** [comment]
ya pas de int inférieur a 32 bits en proto

de toute facon, si la valeur que tu donnes peut etre contenu sur  8 bits, proto encodera en 1 octet
